"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { QualifiedTask } from "../client/daemon-api.ts";
import { groupDaemonTasks, statePresentation, workspaceSearch, type WorkspaceSelection } from "../client/daemon-ui-state.ts";
import type { DaemonConnection } from "../server/daemon-registry.ts";
import { SessionPanel } from "./session-panel.tsx";

export function TaskRail({ connections, tasksByDaemon, offlineByDaemon, selection, login, open, onClose }: { connections: DaemonConnection[]; tasksByDaemon: Record<string, QualifiedTask[]>; offlineByDaemon: Record<string, boolean>; selection: WorkspaceSelection; login: string; open: boolean; onClose: () => void }) {
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});
  const [mobile, setMobile] = useState(false);
  const closeButton = useRef<HTMLButtonElement>(null);
  useEffect(() => { const query = window.matchMedia("(max-width: 760px)"); const update = () => setMobile(query.matches); update(); query.addEventListener("change", update); return () => query.removeEventListener("change", update); }, []);
  useEffect(() => { if (mobile && open) closeButton.current?.focus(); }, [mobile, open]);
  return <aside className="task-rail" aria-label="Tasks" inert={mobile && !open ? true : undefined}><header className="task-rail-header"><Link href="/tasks" className="brand" onClick={onClose}>SF</Link><strong>Software Factory</strong><button ref={closeButton} className="mobile-only" type="button" onClick={onClose} aria-label="Close task navigation">Close</button></header><div className="rail-controls"><Link href={`/tasks${workspaceSearch({ daemonId: selection.daemonId, taskId: null, sessionId: null })}`} className="primary-link" onClick={onClose}>Create task</Link><Link href="/tasks" className="text-link" onClick={onClose}>Daemon settings</Link></div><nav className="rail-scroll" aria-label="Task navigation">{connections.map((daemon) => { const groups = groupDaemonTasks(tasksByDaemon[daemon.id] ?? []); return <section className="rail-daemon" key={daemon.id}><header><Link href={`/tasks${workspaceSearch({ daemonId: daemon.id, taskId: null, sessionId: null })}`} onClick={onClose} aria-current={selection.daemonId === daemon.id ? "page" : undefined}>{daemon.name}</Link><span data-state={offlineByDaemon[daemon.id] ? "failure" : "success"}>{offlineByDaemon[daemon.id] ? "offline" : "online"}</span></header>{groups.map(({ root, sessions }) => { const key = `${daemon.id}:${root.id}`; const expandedGroup = expanded[key] ?? selection.taskId === root.id; return <div className="task-group" key={key}><div className="task-group-row"><button type="button" aria-expanded={expandedGroup} onClick={() => setExpanded((current) => ({ ...current, [key]: !expandedGroup }))}>{expandedGroup ? "-" : "+"}</button><Link className="task-row" data-state={statePresentation(root.state)} href={`/tasks${workspaceSearch({ daemonId: daemon.id, taskId: root.id, sessionId: null })}`} onClick={onClose} aria-current={selection.taskId === root.id && !selection.sessionId ? "page" : undefined}><i /><span><strong>{root.request}</strong><small>{root.state}</small></span></Link></div>{expandedGroup ? <div className="session-tree">{sessions.map((session) => <Link className="task-row task-row-session" data-state={statePresentation(session.state)} key={session.id} href={`/tasks${workspaceSearch({ daemonId: daemon.id, taskId: root.id, sessionId: session.id === root.id ? null : session.id })}`} onClick={onClose} aria-current={(selection.sessionId ?? selection.taskId) === session.id ? "page" : undefined}><i /><span><strong>{session.id === root.id ? "Initial session" : session.request}</strong><small>{session.state}</small></span></Link>)}</div> : null}</div>; })}{!groups.length ? <p className="rail-empty">No tasks loaded.</p> : null}</section>; })}</nav><footer><SessionPanel login={login} /></footer></aside>;
}
